config/routes.rb
Rails.application.routes.draw do






  resources :posts
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'pages#index'

  get 'pages/index'

  get 'pages/Budowa'

  get 'pages/Zapis_Nutowy'

  get 'pages/Jak_grac'

  get 'pages/Symulator'

  get 'pages/O_projekcie'

  get 'pages/Podstawy'

  get 'pages/Gotowe_rytmy'

  get 'pages/Czysta_przyjemnosc'
  
  get 'pages/Usersi'
  
  get 'pages/SymulatorS'
  
  put 'pages/make_admin/:id' => 'pages#make_admin', :as => "make_admin"
  
  put 'pages/take_admin/:id' => 'pages#take_admin', :as => "take_admin"

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_admins

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true



end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify :role_cname => 'Admin'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   attr_accessor :login
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]


         validates :imie, presence: true
         validates :nickname, presence: true
         validates :nazwisko, presence: true
         validates_format_of :nickname, with: /^[a-zA-Z0-9_\.]*$/ , :multiline => true 
         validates_uniqueness_of :nickname
         validates :nickname, :presence => true, :uniqueness => { :case_sensitive => false } # etc.
         has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => ":style/default.png"
         validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
        validates_confirmation_of :password

    def self.find_for_database_authentication(warden_conditions)
        conditions = warden_conditions.dup
        if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(nickname) = :value OR lower(email) = :value", { :value => login.downcase }]).first
        elsif conditions.has_key?(:nickname) || conditions.has_key?(:email)
        where(conditions.to_h).first
        end
    end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end


#mein

  before_action :configure_permitted_parameters, if: :devise_controller?





  def configure_permitted_parameters
    
    added_attrs = [:imie, :nazwisko, :nickname, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: [:imie, :nazwisko, :nickname, :email, :password, :password_confirmation, :remember_me, :avatar]
    
    #devise_parameter_sanitizer.permit(:sign_up, keys: [:imie, :nazwisko, :nickname, :email, :password, :password_confirmation])
    #devise_parameter_sanitizer.permit(:sign_in, keys: [:nickname, :email])
    #devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :email])
  end
  
  private

  # Overwriting the sign_out redirect path method
  def after_sign_in_path_for resource
    pages_O_projekcie_path
  end
  
  def after_sign_out_path_for(resource)
    pages_O_projekcie_path
  end
  
  def after_update_path_for(resource)
   edit_user_registration_path
  end
#mein
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  before_action :require_admin, only: [:Usersi, :make_admin, :take_admin]
  

  def index
     render layout: 'appWithoutBannerAndNavbar'
  end

  def Budowa
  end

  def Zapis_Nutowy
  end

  def Jak_grac

  end

  def Symulator

  end
  
  def SymalatorS
  
  end

  def O_projekcie
    @post = Post.last
  end
  
  def Usersi
    @users = User.all
  end
  
  def make_admin
    @user = User.find(params[:id])
    @user.add_role 'admin'
    respond_to do |format|
      format.html { redirect_to pages_Usersi_path }
      format.js
    end
    
  end
  
  def take_admin
    @user = User.find(params[:id])
    @user.remove_role 'admin'
    respond_to do |format|
      format.html { redirect_to pages_Usersi_path }
      format.js
    end
  end
  

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:create, :new,  :edit, :update, :destroy]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.reverse
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
    
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  

  
  def destroy
      
      if current_user.valid_password?(params[:user][:password_check])
          resource.destroy
          Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
          set_flash_message! :notice, :destroyed
          yield resource if block_given?
          respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
     else
          redirect_to edit_user_registration_path
          flash[:msg] ="Invalidzkie hasło"
      end
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
  def require_admin
    unless current_user && current_user.has_role?(:admin)
      redirect_to root_path
    end
  end
  
  def require_admin?
    current_user && current_user.has_role?(:admin)
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_banner.html.erb
<div  style="height:350px; background-size:100% 100%; background-repeat: no-repeat; background-image:url('<%= image_url "background1.jpeg" -%>');">

</div>

app/views/layouts/_footer.html.erb
<div class="row" id="footer">
  <h4>Copyright by OWG corportaion © All rights reserved</h4>
</div>

app/views/layouts/_login.html.erb
    <a href="#" data-toggle="modal" data-target="#login-modal">Zaloguj się</a>




<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
          <div class="modal-dialog">
            <div class="loginmodal-container">
              <h1 style="margin-bottom:25px;">Zaloguj się</h1>


              <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
              <%= f.error_notification %>
              <%= f.input :login ,:label => 'Nickname lub email', required: true, autofocus: true, input_html: { class: "form-control",} %>
              <%= f.input :password,:label => 'Hasło', required: true %>
              <%= f.input :remember_me,:label => 'Zapamiętaj mnie', as: :boolean if devise_mapping.rememberable? %>
              <%= f.button :submit, "Zaloguj się" %>
                   <%end%>

                <%= link_to new_user_password_path do %>

                    <span>Zapomniałeś hasła?</span>

                <%end%>




                    <%=link_to new_user_registration_path do %>

                    <span style="margin-left:3.5em;">Załóż konto</span>

                  <%end%>






            </div>
        </div>
      </div>

app/views/layouts/_navbar.html.erb
            <nav class="navbar navbar-default">



                <div >

                    <div class="navbar-header">




                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>

                        <%=link_to pages_O_projekcie_path, class:"navbar-brand" do  %>

            &nbsp&nbsp O projekcie

                        <%end%>

                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">



                        <ul class="nav navbar-nav">


                            <li>
                                <%=link_to pages_Budowa_path do %>

                                Na sam początek

                                <%end%>
                            </li>

                            <li>
                                <%=link_to posts_path do %>

                              Ćwiczenia

                                <%end%>
                            </li>

                            <li id="3" class="dropdown">

                                <%=link_to pages_Zapis_Nutowy_path, id:"dropdawn",  class:"dropdown-toggle", role:"button" do %>
                                Zapis Nutowy
                                <span class="caret"></span>

                                <%end%>

                                <ul id="1" class="dropdown-menu" role="menu">

                                    <li>
                                        <%=link_to pages_Podstawy_path do %>

                                        Podstawy

                                        <%end%>

                                    </li>

                                    <li>
                                        <%=link_to pages_Gotowe_rytmy_path do %>

                                        Gotowe rytmy

                                        <%end%>
                                    </li>
                                    <li>
                                        <%=link_to pages_Czysta_przyjemnosc_path do %>

                                        Czysta przyjemność

                                        <%end%>
                                    </li>

                                </ul>
                            </li>

                            <script>

                                document.getElementById("dropdawn").addEventListener("mouseover", mouseOver);
                                document.getElementById("1").addEventListener("mouseover", mouseOver);
                                document.getElementById("dropdawn").addEventListener("mouseout", mouseOut);
                                document.getElementById("3").addEventListener("mouseout", mouseOut);

                                function mouseOver() {
                                    $('#1').stop().slideDown();   //document.getElementById("1").style.display = "block";

                                }

                                function mouseOut() {
                                    $('#1').stop().slideUp();   //document.getElementById("1").style.display = "none";
                                }
                            </script>

                            <li>
                                <%=link_to pages_Jak_grac_path do %>

                                Jak Grać?

                                <%end%>
                            </li>

                            <li>
                                <%=link_to pages_Symulator_path do %>

                                Symulator

                                <%end%>
                            </li>



                        </ul>

                        <ul class="nav  navbar-nav navbar-right">

                            <% if user_signed_in? %>

                    <li class="round-image-50" style="height: 25px;"><%= image_tag current_user.avatar.url(:thumb) , class: 'img-thumbnail', style: 'height: 50px' %></li>

                    <li id="5" class="dropdown">

                                <%=link_to edit_user_registration_path, id:"dropdawn2",  class:"dropdown-toggle", role: 'text' do %>
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp&nbsp&nbsp&nbsp<%=current_user.nickname%>&nbsp
                                <span class="caret"></span>

                                <%end%>

                                    <ul id="4" class="dropdown-menu" role="menu">

                                        <li>
                                    <%=link_to pages_Symulator_path do %>

                                    Symulator

                                    <%end%>

                                        </li>

                                        <li>


                                    <%=link_to pages_Symulator_path do %>

                                    Symulator

                                    <%end%>
                                        </li>
                                    <% if require_admin? %> 
                                        <li>
                                    <%=link_to pages_Usersi_path do %>

                                    Usersi

                                    <%end%>

                                        </li>
                                        <% end %>

                                    </ul>
                                </li>
                                <script>

                                    document.getElementById("dropdawn2").addEventListener("mouseover", mouseOver);
                                    document.getElementById("4").addEventListener("mouseover", mouseOver);
                                    document.getElementById("dropdawn2").addEventListener("mouseout", mouseOut);
                                    document.getElementById("5").addEventListener("mouseout", mouseOut);

                                    function mouseOver() {
                                       $('#4').stop().slideDown();  // document.getElementById("4").style.display = "block";

                                    }

                                    function mouseOut() {
                                       $('#4').stop().slideUp();  // document.getElementById("4").style.display = "none";
                                    }
                                </script>


                            <li>
                                <%= link_to destroy_user_session_path, :method=> :delete do %>
                                Wyloguj się

                                <%end%>
                                <%else%>
                            <li>
                                <%= link_to new_user_registration_path do %>
                                Załóż konto
                                <%end%>
                            </li>
                            <li>
                            <%=render "layouts/login" %>
                            </li>
                            <!-- <li>
                                <%= link_to new_user_session_path do %>
                                Zaloguj się
                                <%end%>
                            </li> -->

                            <% end %>


                        </li>
                    </ul>





                </div>

            </div>


        </nav>

app/views/layouts/appWithoutBannerAndNavbar.html.erb
<!DOCTYPE html>
<html>
    <head>


        <title>DrumsProject</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'index'%>
        <%= javascript_include_tag 'flash'%>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
        <link rel="shortcut icon" href="<%=image_url 'nuta.png'%>" />



    </head>
      <!-- /*<style>
            #view-source {
                position: fixed;
                display: block;
                right: 0;
                bottom: 0;
                margin-right: 40px;
                margin-bottom: 40px;
                z-index: 900;

                      }

        </style>*/ -->
    <body>





        <%= yield %>






</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl-PL">
    <head>

        <title>DrumsProject</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.7/css/bootstrap-dialog.min.css">
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.7/js/bootstrap-dialog.min.js"></script>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
        <link rel="shortcut icon" href="<%=image_url 'nuta.png'%>" />
        <style>
            #view-source {
                position: fixed;
                display: block;
                right: 0;
                bottom: 0;
                margin-right: 40px;
                margin-bottom: 40px;
                z-index: 900;
              }
        </style>
    </head>
    <body id="IdOfWholeDocument">
        <% if notice %>
        <div class="row alert alert-success alert-dismissible" role="alert" id="noticeid">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>Wiadomość:
            </strong><%= notice %>
        </div>
        <%end%>

        <%= render 'layouts/navbar'   %>

        <%=render 'layouts/banner' %>

        <div style="margin-top:15px;">
            <%= yield %>
        </div>

        <%= render 'layouts/footer' %>

    </body>
</html>

app/views/pages/Budowa.html.erb
<h1 style="text-align:center;margin-top:10px;">Początki nie muszą być trudne... (ale będą) </h1>
<div class="jumbotron row" style=" width:90%; margin-left:5%; margin-right:5%; margin-top:2em; ">
  <center style="font-size:2em">Myślisz o rozpoczęciu nauki gry na perkusji ?</center><br>
    <p style="margin-right:1em; margin-left:1em;">
      Nie musisz nawet o tym myśleć, masz dwie ręcę, dwie nogi już masz perkusję tylko jeszce o tym nie wiesz.
Nie męcz rodziców o zestaw perkusjny za nim nie jesteś w 100% pewien, że będziesz chciał grać.
Wiadomo wszystko fajnie wygląda w głowie, ale czy nie pograsz przez 2dni i nie rzucisz go w kąt pokoju ?
Sprawdź, czy to jest to czego szukasz. Dużo początkowych ćwiczeń w zupełności można wykonywać na padzie,
który kosztuje w okolicach 20 zł i pałeczki również tyle samo. A już wtedy sprawdzisz czy to jest dla ciebie.
Oczywiście nie przyniesie to radości z uderzenia w prawdziwą perkusję, ale wprowadzi w początkowy rozwój.
Jeżeli chcesz siąść za bebnąmi i poczuć co niosą ze sobą, zapraszam ;) Albo sprawdź w swoim mieście
dostępnych nauczieli perkusjnych bo pewnie tacy są, muszą być. I się przekonaj, uwaga na słuch.
Głupio byloby nie słyszeć co grasz. Pamiętaj jeżeli coś nie wychodzi na początku to nie znaczy że się do tego nie nadajesz.
Po prostu trzeba obrać inną drogę treningu. Cytując klasyka, który wisi na mojej ścianie " If you can dream it, you can do it ".<br>
Teraz zamknij oczy, oczywiście jak przeczytasz do końca.... wyobraź sobie twoje marzenie związane z perkusją, objętnie co tłum dziewczyn, scenę, własy zespół.
Czy po prostu dobrą zabawę, a teraz wyznacz sobie drogę do tego marzenia, które własnie powstało w twojej głowie i zrób to !
Pamiętaj że samozaparcie jest cenne, ale to jakich ludzi spotkach na swojej drodzę jest też bardzo ważne. Nie zapominaj o swoim normalnym życiu na swojej drodze do kariery.
Polecam oglądnąć film Whiplash.Każdy perkusista chyba go oglądał. Dużo wartości można wyciągnąć z tego filmu.
<br>
<br>
Rozpisałem się jak zawsze, ale w końcu. Dobrze, zaczynajmy.</br>
Poniżej będzie dostępny jeden z najprostszych rytmów perkusyjnych.
Czwórkowy ze stopą na 1 i 3 oraz 2 i 4. Jeżeli nic Ci to nie mówi nie przejmuj sie tym.
Chce pokazać, że naprawdę nie jest to trudne.
<br>
<br>
<br>
Tak tutaj będzie program jak go zrobimy (Michał go zrobi xD)

<br>
<br>
<br>

Jak widziałeś i usłyszałeś prawa ręka uderzała cały czas, a lewa i prawa noga na zmianę równocześnie z prawą.
Spróbuj to wystukać prawa noga z prawą reką i lewa ręką z prawą ręką. I tak powtórzyć z milion razy.
Jeżeli się tego nauczyłeś to już możesz grać dwa znane utowry, m.in.<br> Elton John - I'm Still Standing (Marta xD)  <br>  AC/DC - Back in black
<br>
W dziale zapis nutowy poznasz dlaczego i jak wszystko jest zapisywane. Oczywiście w tym momencie stoisz przed szczytem wielkiej gory, trzeba teraz na niego wejść :)
Mam nadzieję że tym krótkim wstępem ( tak będzie dłuższy) zachęciłem i pokazałem, że nie musi to być trudne jak się wydaje.<br>
Będą się tutaj pojawiać regularnie ćwiczenia jak i bardziej zaawansowane jak i same podstawy jak sobie je przypomnę i filmiki z moim udziałem jak i innych.

</p>
</div>

app/views/pages/Czysta_przyjemnosc.html.erb
<h1>mmmhhh</h1>
<p>Find me in app/views/pages/Zapis_Nutowy.html.erb</p>
???????????????????????????????????????????????????????????????

app/views/pages/Gotowe_rytmy.html.erb
<h1>rytmy</h1>
<p>Find me in app/views/pages/Zapis_Nutowy.html.erb</p>

app/views/pages/Jak_grac.html.erb
<div class="col-lg-6">
<div class="well bs-component">
<ul class="nav nav-tabs">
  <li class="active"><a href="#home" data-toggle="tab">Home</a></li>
  <li><a href="#profile" data-toggle="tab">Profile</a></li>
  <li class="disabled"><a>Disabled</a></li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      Dropdown <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><a href="#dropdown1" data-toggle="tab">Action</a></li>
      <li class="divider"></li>
      <li><a href="#dropdown2" data-toggle="tab">Another action</a></li>
    </ul>
  </li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade active in" id="home">
    <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
  </div>
  <div class="tab-pane fade" id="profile">
    <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit.</p>
  </div>
  <div class="tab-pane fade" id="dropdown1">
    <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork.</p>
  </div>
  <div class="tab-pane fade" id="dropdown2">
    <p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater.</p>
  </div>
</div>
</div>
</div>

app/views/pages/Podstawy.html.erb
<h1>PPodstawy</h1>
<p>Find me in app/views/pages/Zapis_Nutowy.html.erb</p>

app/views/pages/make_admin.js.erb
$('#user<%= @user.id %>').removeClass("label-info").addClass("label-success").html("true");
$('#makeadmin<%= @user.id %>').toggle();
$('#takeadmin<%= @user.id %>').toggle();

app/views/pages/take_admin.js.erb
$('#user<%= @user.id %>').removeClass("label-success").addClass("label-info").html("false");
$('#makeadmin<%= @user.id %>').toggle();
$('#takeadmin<%= @user.id %>').toggle();

app/views/posts/edit.html.erb
<div class="row">
  <div class="container">
        
        <h1>Editing Post</h1>
        
        <%= render 'form', post: @post %>
        <br>
        <%= link_to 'Show', @post, class: 'btn btn-info btn-sm' %> 
        <%= link_to 'Back', posts_path , class: 'btn btn-info btn-sm' %>

    </div>
</div>

app/views/posts/index.html.erb
<div class="row">
    <div class="container" style="width: 80%">
      <div class="jumbotron" style="padding-top: 10px; padding-bottom: 10px;">
          <div class="page-header">
                <div style="float: right;">
                  <%  if require_admin? %>
                  <%= link_to 'Nowy post', new_post_path, class: 'btn btn-info btn-lg' %>
                  <%  end %>
                </div>
              <h1>Ćwiczenia <small>       Pomogą Ci w staniu się lepszym</small></h1>
      
           </div>
      </div>
    </div>
  <div class="container">
      <div style="table-responsive">

          <tbody>
            
            <% @posts.each  do |post| %>
        <div class="jumbotron">
            <div style="float:right;">
              Dodany: <%= l post.created_at, format: '%H:%M:%S , %d %B %Y' %>
            </div>
            <h1><%= post.name %></h1>
            <h3><%= post.title %></h3>
            <hr>
            <p><%= truncate post.content, length: 160 %></p>
            <%  if require_admin? %>
                  <div style="float:right;">
                    <p><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-primary btn-sm' %></p>
                    <p><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></p>
                  </div>
            <%  end %>
            <p><%= link_to 'Dowiedz się więcej', post, class: 'btn btn-primary btn-lg' %></p>
            </div>
            <% end %>
        
          </tbody>
        </table>
        <br>
      </div>

  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
<h1>New Post</h1>

<%= render 'form', post: @post %>
<br>
<%= link_to 'Back', posts_path, class: 'btn btn-info btn-sm' %>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="container">
    <div class="jumbotron">
   <div style="float:right;">
          Dodany: <%= l @post.created_at, format: '%H:%M:%S , %d %B %Y' %>
    </div>
    <h1  style="text-align:center">
      <%= @post.name %>
    </h1>
    
    <h2>
      <%= @post.title %>
    </h2>
    <hr>
    <p>
      <%= @post.content %>
    </p>
    <%  if require_admin? %>
    <%= link_to 'Edit', edit_post_path(@post),class: 'btn btn-info btn-sm' %> 
    <%  end %>
    <%= link_to 'Powrót do listy postów', posts_path,class: 'btn btn-info btn-sm' %>
    </div>
  </div>
</div>